import type { CountryTip } from './types';

export const TIP_COUNTRIES: CountryTip[] = [
  {
    code: 'US',
    name: '미국',
    flag: '🇺🇸',
    currency: 'USD',
    commonTip: 18,
    suggestions: [15, 18, 20, 25],
  },
  {
    code: 'CA',
    name: '캐나다',
    flag: '🇨🇦',
    currency: 'CAD',
    commonTip: 15,
    suggestions: [15, 18, 20],
  },
  {
    code: 'GB',
    name: '영국',
    flag: '🇬🇧',
    currency: 'GBP',
    commonTip: 10,
    suggestions: [10, 12, 15],
  },
  {
    code: 'AU',
    name: '호주',
    flag: '🇦🇺',
    currency: 'AUD',
    commonTip: 10,
    suggestions: [10, 15],
  },
  {
    code: 'DE',
    name: '독일',
    flag: '🇩🇪',
    currency: 'EUR',
    commonTip: 10,
    suggestions: [5, 10, 15],
  },
  {
    code: 'FR',
    name: '프랑스',
    flag: '🇫🇷',
    currency: 'EUR',
    commonTip: 5,
    suggestions: [5, 10],
    note: '서비스료 포함 시 불필요',
  },
  {
    code: 'IT',
    name: '이탈리아',
    flag: '🇮🇹',
    currency: 'EUR',
    commonTip: 10,
    suggestions: [5, 10, 15],
  },
  {
    code: 'ES',
    name: '스페인',
    flag: '🇪🇸',
    currency: 'EUR',
    commonTip: 5,
    suggestions: [5, 10],
  },
  {
    code: 'NL',
    name: '네덜란드',
    flag: '🇳🇱',
    currency: 'EUR',
    commonTip: 10,
    suggestions: [5, 10, 15],
  },
  {
    code: 'SE',
    name: '스웨덴',
    flag: '🇸🇪',
    currency: 'SEK',
    commonTip: 10,
    suggestions: [5, 10, 15],
  },
  {
    code: 'MX',
    name: '멕시코',
    flag: '🇲🇽',
    currency: 'MXN',
    commonTip: 15,
    suggestions: [10, 15, 20],
  },
  {
    code: 'BR',
    name: '브라질',
    flag: '🇧🇷',
    currency: 'BRL',
    commonTip: 10,
    suggestions: [10, 15],
    note: '10% 서비스료 청구 시 별도 불필요',
  },
  {
    code: 'ZA',
    name: '남아프리카',
    flag: '🇿🇦',
    currency: 'ZAR',
    commonTip: 10,
    suggestions: [10, 15],
  },
  {
    code: 'TH',
    name: '태국',
    flag: '🇹🇭',
    currency: 'THB',
    commonTip: 10,
    suggestions: [10, 15],
    note: '고급 레스토랑 권장',
  },
  {
    code: 'SG',
    name: '싱가포르',
    flag: '🇸🇬',
    currency: 'SGD',
    commonTip: 10,
    suggestions: [10, 15],
    note: '서비스료 10% 별도 청구 일반적',
  },
  {
    code: 'HK',
    name: '홍콩',
    flag: '🇭🇰',
    currency: 'HKD',
    commonTip: 10,
    suggestions: [10, 15],
    note: '10% 서비스료 포함 시 불필요',
  },
  {
    code: 'AE',
    name: 'UAE',
    flag: '🇦🇪',
    currency: 'AED',
    commonTip: 10,
    suggestions: [10, 15],
  },
  {
    code: 'IN',
    name: '인도',
    flag: '🇮🇳',
    currency: 'INR',
    commonTip: 10,
    suggestions: [10, 15],
    note: '고급 식당 권장',
  },
  {
    code: 'KR',
    name: '한국',
    flag: '🇰🇷',
    currency: 'KRW',
    commonTip: 0,
    suggestions: [0],
    noTip: true,
    note: '팁 문화 없음',
  },
  {
    code: 'JP',
    name: '일본',
    flag: '🇯🇵',
    currency: 'JPY',
    commonTip: 0,
    suggestions: [0],
    noTip: true,
    note: '팁을 거절하는 문화',
  },
  {
    code: 'CN',
    name: '중국',
    flag: '🇨🇳',
    currency: 'CNY',
    commonTip: 0,
    suggestions: [0],
    noTip: true,
    note: '팁 문화 없음',
  },
];
